// angular-pearl-widget/projects/pearl-widget/src/lib/pearl-widget.ts
import {
  Component,
  ElementRef,
  Input,
  ViewChild,
  AfterViewInit
} from '@angular/core';
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';

@Component({
  selector: 'pearl-widget',
  template: `
    <iframe
      #iframeRef
      title="Pearl Widget"
      [src]="iframeSrc"
      style="width: 100%; height: 100%; border: none;"
    ></iframe>
  `
})
export class PearlWidget implements AfterViewInit {
  @Input() accessKey?: string;
  @Input() mode?: string;

  @ViewChild('iframeRef', { static: true }) iframeRef!: ElementRef<HTMLIFrameElement>;

  widgetOrigin = 'https://www.pearl.com';
  iframeSrc: SafeResourceUrl;

  constructor(private sanitizer: DomSanitizer) {
    this.iframeSrc = this.sanitizer.bypassSecurityTrustResourceUrl(`${this.widgetOrigin}/api/widget`);
  }

  ngAfterViewInit(): void {
    const iframe = this.iframeRef?.nativeElement;
    if (iframe && this.accessKey && this.mode) {
      iframe.addEventListener('load', () => {
        iframe.contentWindow?.postMessage(
          {
            type: 'init',
            payload: {
              accessKey: this.accessKey,
              mode: this.mode,
            },
          },
          this.widgetOrigin
        );
      });
    }
  }
}

// react-pearl-widget/pearl-widget/src/PearlWidget.tsx
import React, { useRef } from "react";

export interface PearlWidgetProps {
    accessKey?: string;
    mode?: string; // Use one the available mods: expert, pearl-ai, pearl-ai-verified, pearl-ai-expert
}

export const PearlWidget = (props: PearlWidgetProps) => {
  const iframeRef = useRef<HTMLIFrameElement>(null);
  const widgetOrigin = 'https://www.pearl.com';

  //Inits chat when iframe loads
  const handleLoad = () => {
    if (iframeRef.current && props?.accessKey && props?.mode) {
      iframeRef.current?.contentWindow?.postMessage(
         {
            type: 'init',
            payload: {accessKey: props.accessKey, mode: props.mode}
        },
        widgetOrigin
      );
    }
  };

  return (
    <iframe
        title="Pearl Widget"
        style={{ width: "100%", height: "100%", border: "none" }}
        src={`${widgetOrigin}/api/widget`}
        ref={iframeRef}
        onLoad={handleLoad}
    />
  );
}
