// react-pearl-widget/sample-app/src/App.tsx
import "./App.css";
import { PearlWidget } from "@pearl.com/pearl-widget-react";

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <h1>Pearl Chat Widget Example</h1>
      </header>
      <div className="App-widget">
        <PearlWidget accessKey="your-access-key" mode="pearl-ai"/>
      </div>
    </div>
  );
}

export default App;

// angular-pearl-widget/projects/sample-app/src/app/app.ts
import { Component } from '@angular/core';
import { PearlWidget } from '@pearl.com/pearl-widget-angular';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, PearlWidget],
  template: `
    <h1>Pearl Chat Widget Example</h1>
    <div class="widget">
      <pearl-widget
        [accessKey]="'YOUR_PEARL_ACCESS_KEY'"
        [mode]="'pearl-ai'"
      ></pearl-widget>
    </div>
  `,
  styles: `
    .widget {
      width: 800px;
      height:600px;
    }
  `,
})
export class App {}
